"""Git hook installation and management module."""

import os
import stat
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console()

# Post-commit hook content
HOOK_TEMPLATE = """#!/bin/bash
# CodeDNA post-commit hook
# Automatically generated by codedna.
#
# Bind stdin directly to the terminal (/dev/tty) so the survey works.
# Git hooks sometimes redirect stdin to a closed/empty stream;
# without this line, IntPrompt immediately raises EOFError and silently skips the survey.
#
# Conditions:
#   [ -t 1 ]        → stdout is connected to a terminal (false in CI/pipe → survey skipped, correct)
#   [ -r /dev/tty ] → /dev/tty is actually readable
if [ -t 1 ] && [ -r /dev/tty ]; then
    exec < /dev/tty
fi

# Check if codedna is in PATH
if command -v codedna &> /dev/null; then
    codedna status --hook
else
    # Try running via uv (for development environments)
    REPO_ROOT="$(git rev-parse --show-toplevel)"
    if [ -f "$REPO_ROOT/.venv/bin/codedna" ]; then
        "$REPO_ROOT/.venv/bin/codedna" status --hook
    elif [ -f "$HOME/.local/bin/codedna" ]; then
        "$HOME/.local/bin/codedna" status --hook
    else
        echo "[CodeDNA] 'codedna' command not found. Try: pip install codedna"
    fi
fi
"""


def find_git_root(start_path: Optional[Path] = None) -> Optional[Path]:
    """
    Search upward from the given path for a .git directory.

    Args:
        start_path: Starting point for the search (defaults to current directory)

    Returns:
        Repo root containing .git directory, or None
    """
    path = Path(start_path or Path.cwd()).resolve()
    for parent in [path, *path.parents]:
        if (parent / ".git").exists():
            return parent
    return None


def install_hook(repo_path: Optional[Path] = None) -> bool:
    """
    Install the post-commit hook.

    Args:
        repo_path: Git repo root directory (auto-detected if None)

    Returns:
        True if installed successfully
    """
    root = repo_path or find_git_root()
    if not root:
        console.print("[bold red]Error:[/bold red] Git repo not found. Run 'git init' first.")
        return False

    hooks_dir = root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_file = hooks_dir / "post-commit"

    # Back up existing hook if present
    if hook_file.exists():
        backup = hooks_dir / "post-commit.backup"
        hook_file.rename(backup)
        console.print(f"[yellow]Existing hook backed up:[/yellow] {backup}")

    # Write new hook
    hook_file.write_text(HOOK_TEMPLATE, encoding="utf-8")

    # Make executable (chmod +x)
    current_mode = hook_file.stat().st_mode
    hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    console.print(f"[green]✓[/green] Hook installed: {hook_file}")
    return True


def uninstall_hook(repo_path: Optional[Path] = None) -> bool:
    """
    Remove the post-commit hook.

    Args:
        repo_path: Git repo root directory (auto-detected if None)

    Returns:
        True if removed successfully
    """
    root = repo_path or find_git_root()
    if not root:
        console.print("[bold red]Error:[/bold red] Git repo not found.")
        return False

    hook_file = root / ".git" / "hooks" / "post-commit"

    if not hook_file.exists():
        console.print("[yellow]Post-commit hook not found, already removed.[/yellow]")
        return True

    # Restore from backup if available
    backup = root / ".git" / "hooks" / "post-commit.backup"
    if backup.exists():
        hook_file.unlink()
        backup.rename(hook_file)
        console.print("[green]✓[/green] Previous hook restored.")
    else:
        hook_file.unlink()
        console.print("[green]✓[/green] CodeDNA hook removed.")

    return True


def install_ci_workflow(repo_path: Optional[Path] = None) -> bool:
    """
    Write the GitHub Actions CI template to the repo.

    Args:
        repo_path: Git repo root directory (auto-detected if None)

    Returns:
        True if written successfully
    """
    root = repo_path or find_git_root()
    if not root:
        console.print("[bold red]Error:[/bold red] Git repo not found.")
        return False

    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    target = workflows_dir / "codedna.yml"

    if target.exists():
        console.print("[yellow]⚠[/yellow]  .github/workflows/codedna.yml already exists, not overwriting.")
        return True

    # Copy template bundled with the package
    try:
        template_path = Path(__file__).parent.parent / ".github" / "workflows" / "codedna.yml"
        if template_path.exists():
            target.write_text(template_path.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            # Fallback: inline template
            target.write_text(_CI_TEMPLATE, encoding="utf-8")
        console.print(f"[green]✓[/green] CI template created: [dim]{target}[/dim]")
        return True
    except Exception as e:
        console.print(f"[red]✗[/red] Failed to write CI template: {e}")
        return False


# GitHub Actions template content (fallback)
_CI_TEMPLATE = """\
name: CodeDNA Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  analyze:
    name: AI Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install codedna
      - run: codedna scan
        continue-on-error: true
      - name: High-risk check
        run: |
          codedna scan --min-risk 0.7 && echo "✅ No high-risk files." || echo "⚠️ High-risk files detected."
        continue-on-error: true
"""


def is_hook_installed(repo_path: Optional[Path] = None) -> bool:
    """Check whether the CodeDNA hook is installed."""
    root = repo_path or find_git_root()
    if not root:
        return False
    hook_file = root / ".git" / "hooks" / "post-commit"
    if not hook_file.exists():
        return False
    content = hook_file.read_text(encoding="utf-8", errors="replace")
    return "CodeDNA" in content
